# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0428aa2aeb431b39821c9195b33f476d71da6783ee063c3bc54fe3de9a319ed1b997a15b8801d7cc05dbb069ea7d40abd7b0ff3465f78bd813961fef4b0e0b37

test:
  secret_key_base: 67c7e65e9478bac19bea1f5cb0dd23ebd50fa7fada426bb31a90d04bbc5dcf8c1afb958790e0494571d675b4d6c5a0233597f10032c8b5e1ad1d1bfd565a2dc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
